### ISSUE TITLE
Won't compile on Centos 7

### ISSUE THREAD

**Issue by inalto** [mind04/mod-ruid2#10]
mod_ruid2.c:51:28: fatal error: sys/capability.h: No such file or directory
i tried to change it to linux/capability.h but some declarations are missing or not available:

'CAP_EFFECTIVE' 
'CAP_SET'
'CAP_CLEAR'

i tried to grep them in /usr/include without finding them.

**Comment by mind04** [comment]
I will after you install the required header files. 
'yum provides *sys/capability.h' will give you a clue what to install.

**Comment by inalto** [comment]
Hello,
sorry for the wrong issue notificaiton, just figure it out that i confused libpcap-devel with libcap-devel!

Thank you!! :+1:

**Comment by omadjoudj** [comment]
Just for info, I've packaged mod_ruid2 for Fedora and EPEL.

you should be able to install it with:

```
  yum -y install epel-release
  yum -y install mod_ruid2
```
