### ISSUE TITLE
uid set to 4294967295 on CentOS Apache 2.2

### ISSUE THREAD

**Issue by SalehObaid** [mind04/mod-ruid2#3]
Hello
i have installed mod_ruid2 on CentOS 6.4 ( x86_64 ) mod_php.
after configuring the virtual host with:
RMode config 
RUidGid root root

OR

RMode stat
and chmod root.root test.php

---

a php script contain:
## <? echo `id`; ?>

always return this:

uid=4294967295 gid=4294967295 groups=48(apache) 

it was expected to return uid=0 gid=0 !

**Comment by mind04** [comment]
I need more information:
- What version of mod_ruid2 is this.
- What additional mod_ruid2 options are in your configuration (without a 'RMinUidGid 0 0' switching to root is impossible)

**Comment by SalehObaid** [comment]
Hello

# 

Q: What version of mod_ruid2 is this?
A: latest version from githup master branch.

# 

Q: What additional mod_ruid2 options are in your configuration?
A: 

``` php
LoadModule ruid2_module       /usr/lib64/httpd/modules/mod_ruid2.so
LoadModule php5_module        /usr/lib64/httpd/modules/libphp5.so
User apache
Group apache
RMinUidGid root root
<VirtualHost *:80>
        DocumentRoot "/opt/www/test.com"
        ServerName test.com
        <Directory "/opt/www/test.com">
                Options All
                AllowOverride All
                Order allow,deny
                Allow from all
                RMode config
                RUidGid root root
        </Directory>
</VirtualHost>
```

# 

by the way using : ( RMinUidGid 0 0 ) apache wont start, error:

Starting httpd: httpd: bad user name 0 [FAILED]

is this normal? i use  ( RMinUidGid root root ) so i can start apache.

# 

Note: setting mod_ruid to use other user than root works fine.

RUidGid asterisk asterisk <===== OK Working

if you need extra information , just tell me.

**Comment by mind04** [comment]
I'm unable to reproduce your problem with current git master and the provided config example. 
Are you sure the source is unmodified and is current git master? 

BTW Mod_ruid2 does not overload the server config to the virtual hosts the 'RMinUidGid root root' must be paced inside the virtual host.

**Comment by SalehObaid** [comment]
today i installed the module in another server, same hardware, configuration as the old server, and root is working!

thanks for your help
